name: Hangover Build (ARM64) - From Source (native-first with fallback)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'hangover/**'
      - '.github/workflows/build-arm64.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'hangover/**'
      - '.github/workflows/build-arm64.yml'
  workflow_dispatch: {}

jobs:
  build-native:
    name: Native ARM64 build (ubuntu-24.04-arm)
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    if: github.event.repository.private == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            git curl wget ca-certificates gnupg \
            wine wine32 wine64 libwine libwine-dev \
            xvfb x11vnc fluxbox xterm \
            libc6-dev libgcc-s1 libstdc++6 \
            libx11-6 libxext6 libxrender1 libxrandr2 libxss1 libxtst6 libxi6 libxinerama1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxpm4 libxmu6 libxft2 libxau6 libxdmcp6 libxxf86vm1 \
            fonts-dejavu-core fonts-liberation

      - name: Build hangover wine
        working-directory: hangover
        run: |
          mkdir -p wine/build
          cd wine/build
          ../configure --disable-tests --with-mingw=clang --enable-archs=arm64ec,aarch64,i386
          make -j"$(nproc)"

      - name: Tar artifacts
        run: |
          mkdir -p artifact
          tar -C hangover -cvf artifact/hangover_build_arm64.tar wine/build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hangover-build-arm64
          path: artifact/hangover_build_arm64.tar

  build-fallback:
    name: Fallback emulated build (ubuntu-24.04 + cross/QEMU)
    runs-on: ubuntu-24.04
    needs: build-native
    if: github.event.repository.private == true || needs.build-native.result != 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU (arm64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            git curl wget ca-certificates gnupg \
            binfmt-support qemu-user-static \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            fonts-dejavu-core fonts-liberation

      - name: Build in aarch64 container
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use --driver docker-container
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 -f- . -t tmp/build-hangover:arm64 --load <<'DOCKERFILE'
          FROM --platform=linux/arm64 debian:bookworm-slim
          RUN apt-get update && apt-get install -y \
              build-essential cmake ninja-build pkg-config git curl wget ca-certificates gnupg \
              wine wine32 wine64 libwine libwine-dev \
              xvfb x11vnc fluxbox xterm \
              libc6-dev libgcc-s1 libstdc++6 \
              libx11-6 libxext6 libxrender1 libxrandr2 libxss1 libxtst6 libxi6 libxinerama1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxpm4 libxmu6 libxft2 libxau6 libxdmcp6 libxxf86vm1 \
              fonts-dejavu-core fonts-liberation && rm -rf /var/lib/apt/lists/*
          WORKDIR /src
          COPY . .
          WORKDIR /src/hangover
          RUN mkdir -p wine/build && cd wine/build && \
              ../configure --disable-tests --with-mingw=clang --enable-archs=arm64ec,aarch64,i386 && \
              make -j"$(nproc)"
          DOCKERFILE
          id=$(docker create tmp/build-hangover:arm64)
          mkdir -p artifact
          docker cp "$id":/src/hangover/wine/build ./artifact/wine_build
          docker rm "$id"
          tar -C artifact -cvf artifact/hangover_build_arm64.tar wine_build

      - name: Upload artifacts (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: hangover-build-arm64-fallback
          path: artifact/hangover_build_arm64.tar
